--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JeroGamingYT-pm-pl/MultiPlayerCounter
build-by-default: true
branches:
- stable
- PM4
projects:
  MultiPlayerCounter:
    icon: icon.png
    path: ""
    libs:
      - src: jasonwynn10/libpmquery/libpmquery
        version: ^0.1.0
    lint:
      phpstan: false
...
