name: MultiPlayerCounter
main: JeroGamingYT\MultiPlayerCounter\Main
api: 4.0.0
version: 0.0.2
author: JeroGamingYT
website: https://github.com/EricGamingYT

commands:
  multiplayercounter:
    permission: multiplayercounter.command
    description: "MultiPlayerCounter Command"
    aliases: ['mpc']
    
permissions:
  multiplayercounter.command:
    description: "MultiPlayerCounter Command"
    default: op
